In [1]:
import tensorflow as tf 

In [3]:
x = tf.constant(3)
print(x)

tf.Tensor(3, shape=(), dtype=int32)


In [4]:
x = tf.constant(10, shape=(1, 4), dtype='float32')
print(x)

tf.Tensor([[10. 10. 10. 10.]], shape=(1, 4), dtype=float32)


In [6]:
x = tf.ones(4)
print(x)

tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)


In [8]:
x = tf.zeros(4)
print(x)

tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float32)


In [9]:
x = tf.zeros((4, 3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [10]:
x = tf.random.uniform((2, 2), minval=0, maxval=-1)
print(x)

tf.Tensor(
[[-0.5724386  -0.34157252]
 [-0.4651798  -0.7663202 ]], shape=(2, 2), dtype=float32)


In [12]:
x = tf.random.normal((2, 3), mean=0, stddev=-1)
print(x)

tf.Tensor(
[[-1.2888676   0.3652407   0.37668413]
 [ 1.054569   -0.78506076  1.4752641 ]], shape=(2, 3), dtype=float32)


In [14]:
x = tf.range(9) 
x = tf.range(start=0, limit=10, delta=2) 
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [15]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

In [16]:
print(x - y)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [17]:
print(tf.subtract(x, y))

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [18]:
print(tf.multiply(x, y))

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [19]:
print(x * y)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [27]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 5))

In [28]:
print(x, y)

tf.Tensor(
[[-0.7605229  -1.4553102  -0.48465165]
 [ 1.1036249   0.77123934 -0.34752432]], shape=(2, 3), dtype=float32) tf.Tensor(
[[-2.2152438   1.7516863  -2.051733    1.0346309  -1.0272943 ]
 [-0.7250714  -1.0824709  -0.52423155  0.47520977 -1.25129   ]
 [-1.3767953   1.0521885  -0.5931141  -0.5436232  -0.4073827 ]], shape=(3, 5), dtype=float32)


In [29]:
print(tf.matmul(x, y))

tf.Tensor(
[[ 3.4072134 -0.2668115  2.610763  -1.2149702  2.7997346]
 [-2.525532   0.7326996 -2.4625301  1.6972673 -1.9572163]], shape=(2, 5), dtype=float32)


In [30]:
print(x @ y)

tf.Tensor(
[[ 3.4072134 -0.2668115  2.610763  -1.2149702  2.7997346]
 [-2.525532   0.7326996 -2.4625301  1.6972673 -1.9572163]], shape=(2, 5), dtype=float32)


In [32]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices) 

In [33]:
x_indices

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>